language: php

php:
    - 5.5
    - 5.6
    - 7.0

sudo: false

before_install:
    - composer selfupdate

install: composer update --no-interaction

notifications:
    email: kostas.christofilos@rocketgraph.com