parameters:
    connection: live #sandbox or live type of connection
    show_errors: true
    report_assets: assets
    storage_path: storage
    proxy_path: proxy
    connectors_api:
        host: 192.168.10.14
        version: v1