services:
    connector_service:
        class: RG\ConnectorService
        arguments: ["%connectors%", "@api", "@proxy_service", "%connection%", "%responses%"]
    report_service:
        class: RG\ReportService
        arguments: ["@connector_service", "@storage_service", "@event_dispatcher", "@logger", "@report_templating_helper", "%src_path%", "%app_path%"]
    event_dispatcher:
        class: RAM\EventDispatcher\EventDispatcher
        arguments: ["@service_container"]
    report_templating_helper:
        class: RG\RenderEngine\ReportTemplatingHelper
        arguments: ["%report_assets%", "%web_path%", "https://rocketgraph.com/sw" ]
    storage_service:
        class: RAM\Services\Storage
        arguments: ["%storage_path%"]
    proxy_service:
        class: RG\Proxy
        arguments: ["%proxy_path%"]
    post_render_report_listener:
        class: RG\EventListener\PostRenderReportListener
        tags:
            - { name: kernel.event_listener, event: report.post_render, method: onReportRender }
        arguments: ["@report_templating_helper"]
    spelling_service:
        class: RAM\Services\SpellingService
    logger:
        class: RAM\Services\Logger
    http_client:
        class: GuzzleHttp\Client
    api:
        class: RG\Api
        arguments: ["@http_client", "%connectors_api%"]
